<!--- theme: jekyll-theme-minimal --->
title: [openSIM homepage]
description: [webpage containing openSIM documentation test]

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
